### ISSUE TITLE
[FE] Implement useContext hook

### ISSUE THREAD

**Issue by tenthwalker** [Tavern-Keeper-2308/tavern-keeper-fe#49]
[Relevant lesson](https://frontend.turing.edu/lessons/module-3/advanced-react-hooks.html)
In App.js
![Image](https://github.com/Tavern-Keeper-2308/tavern-keeper-fe/assets/139941423/1ad5e305-2135-4de2-a3fb-5f885858450c)

create an `encounterContext.js` file in `/src`, with the following code, then import into files where context will be used to bring in a piece of state, which should be set in App with encounters:
```import React, { createContext } from 'react'

const EncounterContext = createContext()

export default EncounterContext;```

**Comment by ericahagle** [comment]
Turns out this isn't necessary. Closing ticket as wontdo.
